version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: pine613/java-cf-cli:openjdk8
    steps:
      - checkout
      - restore_cache:
          key: profile-website-{{ .Branch }}-{{ checksum "build.sbt" }}
      - run:
          name: System information
          command: |
            java -version
      - run:
          name: Run build
          command: cat /dev/null | ./sbt dist
      - save_cache:
          key: profile-website-{{ .Branch }}-{{ checksum "build.sbt" }}
          paths:
            - ~/.ivy2
            - ~/.sbt
      - deploy:
          name: Deploy to IBM Bluemix
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cf -v
              cf api https://api.au-syd.bluemix.net
              cf login -u $BLUEMIX_USER -p $BLUEMIX_PASSWORD

              for i in {1..3}; do
                cf push && break
              done
            fi
