---

spring:
  profiles:
    active: local
  thymeleaf:
    mode: HTML
  output:
    ansi:
      enabled: always
  resources:
    cache:
      cachecontrol:
        cache-public: true
        max-age: 31536000 # 1 year
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

---

spring.profiles: local
spring.profiles.include:
  - anime
  - app

---

spring.profiles: prod
spring.profiles.include:
  - anime
  - app
