mountain:
  climbed:
    - name: 高尾山
      height: 599
      climbed-at: 2017-06
    - name: 榛名山
      height: 1449
      climbed-at: 2017-06
    - name: '八ヶ岳: 赤岳, 阿弥陀岳'
      height: 2899
      climbed-at: 2017-07
    - name: 大菩薩嶺
      height: 2056
      climbed-at: 2017-08
    - name: 富士山
      height: 3776
      climbed-at: 2017-08
    - name: 筑波山
      height: 877
      climbed-at: 2018-04
    - name: 大岳山
      height: 1266
      climbed-at: 2018-04
    - name: 御岳山
      height: 929
      climbed-at: 2018-04
    - name: 塔ノ岳
      height: 1491
      climbed-at: 2018-05
    - name: 不忘山
      height: 1705
      climbed-at: 2018-06
    - name: 富士山
      height: 3776
      climbed-at: 2018-07
    - name: 雲取山
      height: 2017
      climbed-at: 2018-09
    - name: 於茂登岳
      height: 525
      climbed-at: 2019-03
    - name: 韓国岳
      height: 1700
      climbed-at: 2019-03
    - name: 甲州高尾山
      height: 1106
      climbed-at: 2019-06
    - name: '大雪山: 旭岳'
      height: 2291
      climbed-at: 2019-06
    - name: 入笠山
      height: 1955
      climbed-at: 2019-07
    - name: 高尾山
      height: 599
      climbed-at: 2019-07
    - name: '八ヶ岳: 北横岳'
      height: 2480
      climbed-at: 2019-07
    - name: 富士山
      height: 3776
      climbed-at: 2019-07
    - name: 御嶽山
      height: 3067
      climbed-at: 2019-08
    - name: 燕岳
      height: 2763
      climbed-at: 2019-09
    - name: 大天井岳
      height: 2922
      climbed-at: 2019-09
    - name: '八ヶ岳: 硫黄岳'
      height: 2760
      climbed-at: 2019-12
    - name: 谷川岳
      height: 1977
      climbed-at: 2020-02
    - name: 高尾山
      height: 599
      climbed-at: 2020-08
    - name: 比叡山
      height: 848
      climbed-at: 2020-09
    - name: 高尾山
      height: 599
      climbed-at: 2020-12
    - name: 大菩薩峠
      height: 1897
      climbed-at: 2021-01
    - name: 筑波山
      height: 877
      climbed-at: 2021-01
    - name: 大山 (神奈川県)
      height: 1252
      climbed-at: 2021-02
    - name: 鋸山
      height: 329
      climbed-at: 2021-03
    - name: 陣馬山
      height: 854
      climbed-at: 2021-05
    - name: 棒ノ折山
      height: 969
      climbed-at: 2021-06
    - name: 伊豆ヶ岳
      height: 850
      climbed-at: 2021-07
    - name: 瑞牆山
      height: 2230
      climbed-at: 2021-07
    - name: "阿蘇山: 烏帽子岳"
      height: 1337
      climbed-at: 2021-07
    - name: 乾徳山
      height: 2031
      climbed-at: 2021-08
    - name: 富士山
      height: 3776
      climbed-at: 2021-08
    - name: 陣馬山
      height: 854
      climbed-at: 2021-08
    - name: 富士山
      height: 3776
      climbed-at: 2021-09
    - name: 高水山
      height: 759
      climbed-at: 2021-10
    - name: 岩茸石山
      height: 793
      climbed-at: 2021-10
    - name: 惣岳山
      height: 756
      climbed-at: 2021-10
    - name: 北岳
      height: 3193
      climbed-at: 2021-10
