---

spring:
  profiles:
    default: local
  config:
    import:
      - 'classpath:anime.yml'
      - 'classpath:app.yml'
      - 'classpath:mountain.yml'
  freemarker:
    prefer-file-system-access: false
  output:
    ansi:
      enabled: always
  web:
    resources:
      cache:
        cachecontrol:
          cache-public: true
          max-age: 31536000 # 1 year
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

---

spring:
  config:
    activate:
      on-profile: prod

server:
  error:
    whitelabel:
      enabled: false

---
