anime:
  watched:
    1998:
      - serial experiments lain
    2001:
      - NOIR
    2002:
      - 攻殻機動隊 STAND ALONE COMPLEX
      - フルメタル・パニック!
    2003:
      - D.C. ～ダ・カーポ～
      - プラネテス
      - 真月譚 月姫
      - 無人惑星サヴァイヴ
    2004:
      - この醜くも美しい世界
      - ローゼンメイデン
      - 神無月の巫女
      - 攻殻機動隊 S.A.C. 2nd GIG
      - 魔法少女リリカルなのは
      - 妄想代理人
    2005:
      - AIR
      - D.C.S.S. ～ダ・カーポ セカンドシーズン～
      - LOVELESS
      - SHUFFLE!
      - イリヤの空、UFOの夏
      - かみちゅ!
      - 苺ましまろ
      - 灼眼のシャナ
      - 撲殺天使ドクロちゃん
      - 魔法少女リリカルなのはA's
    2006:
      - Fate/stay night
      - Kanon
      - Soul Link
      - Strawberry Panic
      - xxxHOLiC
      - うたわれるもの
      - ゼロの使い魔
      - はぴねす!
      - ひぐらしのなく頃に
      - 攻殻機動隊 STAND ALONE COMPLEX Solid State Society
      - 涼宮ハルヒの憂鬱
      - 半分の月がのぼる空
      - 夜明け前より瑠璃色な
    2007:
      - DARKER THAN BLACK -黒の契約者-
      - School Days
      - SHUFFLE! MEMORIES
      - sola
      - Venus Versus Virus
      - この青空に約束を― ～ようこそつぐみ寮へ～
      - ご愁傷さま二ノ宮くん
      - ゼロの使い魔～双月の騎士～
      - ななついろ★ドロップス
      - のだめカンタービレ
      - ひだまりスケッチ
      - ひとひら
      - まなびストレート!
      - みなみけ
      - もえたん
      - らき☆すた
      - 苺ましまろ OVA
      - 京四郎と永遠の空
      - 灼眼のシャナII
      - 撲殺天使ドクロちゃん2
      - 魔法少女リリカルなのはStrikerS
    2008:
      - CHAOS;HEAD
      - xxxHOLiC◆継
      - かんなぎ
      - とある魔術の禁書目録
      - シャングリラ
      - のだめカンタービレ 巴里編
    2009:
      - DARKER THAN BLACK -流星の双子-
      - 咲-Saki-
      - スラップアップパーティー -アラド戦記-
      - そらのおとしもの
      - とある科学の超電磁砲
      - にゃんこい!
      - 苺ましまろ encore
      - 空中ブランコ
      - 灼眼のシャナS
    2010:
      - DARKER THAN BLACK-黒の契約者- 外伝
      - 荒川アンダー ザ ブリッジ
      - 荒川アンダー ザ ブリッジx2
      - Angel Beats!
      - 俺の妹がこんなに可愛いわけがない
      - 神のみぞ知るセカイ
      - 侵略!イカ娘
      - 生徒会の一存
      - そらのおとしものf
      - 探偵オペラ ミルキィホームズ
      - のだめカンタービレ フィナーレ
      - 迷い猫オーバーラン!
    2011:
      - DOG DAYS
      - GOSICK -ゴシック-
      - IS 〈インフィニット・ストラトス〉
      - STEINS;GATE
      - 神のみぞ知るセカイII
      - これはゾンビですか?
      - 灼眼のシャナIII (Final)
      - フラクタル
      - 魔法少女まどか☆マギカ
      - 未来日記
      - 夢喰いメリー
      - ロウきゅーぶ!
    2012:
      - Another
      - PSYCHO-PASS サイコパス
      - 咲-Saki- 阿知賀編 episode of side-A
      - 人類は衰退しました
      - 生徒会の一存 Lv.2
      - ゼロの使い魔F
      - 探偵オペラ ミルキィホームズ 第2幕
    2013:
      - Fate/kaleid liner プリズマ☆イリヤ
      - D.C.III ～ダ・カーポIII～
      - 石田とあさくら
      - 俺の彼女と幼なじみが修羅場すぎる
      - 俺の脳内選択肢が、学園ラブコメを全力で邪魔している
      - きんいろモザイク
      - 幻影ヲ駆ケル太陽
      - ダンガンロンパ 希望の学園と絶望の高校生 The Animation
      - とある科学の超電磁砲S
      - 東京レイヴンズ
      - 凪のあすから
      - のんのんびより
      - 変態王子と笑わない猫。
      - 機巧少女は傷つかない
      - 問題児たちが異世界から来るそうですよ？
      - ラブライブ！
      - ロウきゅーぶ！SS
      - ヤマノススメ
    2014:
      - Fate/kaleid liner プリズマ☆イリヤ 2wei!
      - PSYCHO-PASS サイコパス 2
      - selector infected WIXOSS
      - SHIROBAKO
      - アカメが斬る！
      - 悪魔のリドル
      - 彼女がフラグをおられたら
      - グラスリップ
      - グリザイアの果実
      - 月刊少女野崎くん
      - 極黒のブリュンヒルデ
      - ご注文はうさぎですか？
      - 咲-Saki- 全国編
      - 桜Trick
      - さばげぶっ！
      - 人生相談テレビアニメーション「人生」
      - スペース☆ダンディ
      - 星刻の竜騎士
      - 生徒会役員共＊
      - 精霊使いの剣舞
      - 東京喰種
      - となりの関くん
      - ニセコイ
      - のうりん
      - ノーゲーム・ノーライフ
      - ハナヤマタ
      - ばらかもん
      - 棺姫のチャイカ
      - ひめゴト
      - 普通の女子校生が【ろこどる】やってみた。
      - ブラック・ブレット
      - まじもじるるも
      - 魔法科高校の劣等生
      - マンガ家さんとアシスタントさんと
      - ラブライブ！ (第2期)
      - 六畳間の侵略者!?
      - ヤマノススメ セカンドシーズン
      - 結城友奈は勇者である
    2015:
      - Charlotte
      - Fate/kaleid liner プリズマ☆イリヤ ツヴァイ ヘルツ！
      - アブソリュート・デュオ
      - 俺がお嬢様学校に「庶民サンプル」としてゲッツされた件
      - 終わりのセラフ
      - 学戦都市アスタリスク
      - がっこうぐらし!
      - グリザイアの楽園
      - ご注文はうさぎですか？？
      - 冴えない彼女の育て方
      - 銃皇無尽のファフニール
      - 城下町のダンデライオン
      - 聖剣使いの禁呪詠唱
      - 'ニセコイ: (2期)'
      - のんのんびより りぴーと
      - ハロー!!きんいろモザイク
      - 干物妹！うまるちゃん
      - 監獄学園
      - ゆるゆり さん☆ハイ！
      - レーカン!
    2016:
      - 12歳。〜ちっちゃなムネのトキメキ〜
      - Fate/kaleid liner プリズマ☆イリヤ ドライ!!
      - NEW GAME!
      - Lostorage incited WIXOSS
      - Occultic;Nine -オカルティック・ナイン-
      - planetarian～ちいさなほしのゆめ～
      - Re：ゼロから始める異世界生活
      - ViVid Strike！
      - 蒼の彼方のフォーリズム
      - 亜人(第1クール)
      - 亜人(第2クール)
      - あにトレ！ＸＸ～ひとつ屋根の下で～
      - あんハピ♪
      - ガーリッシュ ナンバー
      - クオリディア・コード
      - くまみこ
      - 紅殻のパンドラ
      - 甲鉄城のカバネリ
      - この素晴らしい世界に祝福を
      - この美術部には問題がある！
      - 最弱無敗の神装機竜
      - 三者三葉
      - 終末のイゼッタ
      - 少女たちは荒野を目指す
      - ステラのまほう
      - だがしかし
      - 田中くんはいつもけだるげ
      - ダンガンロンパ3 -The End of 希望ヶ峰学園-未来編
      - ダンガンロンパ3 -The End of 希望ヶ峰学園-絶望編
      - ネトゲの嫁は女の子じゃないと思った？
      - 灰と幻想のグリムガル
      - ハイスクール・フリート
      - ハルチカ 〜ハルタとチカは青春する〜
      - ふらいんぐうぃっち
      - 僕だけがいない街
      - 魔法少女育成計画
      - 魔法少女なんてもういいですから
      - 迷家‐マヨイガ‐
      - 無彩限のファントム ワールド
      - ももくり
      - ラクエンロジック
      - ラブライブ! サンシャイン!!
    2017:
      - BanG Dream!
      - CHAOS;CHILD
      - NEW GAME
      - One Room
      - アイドル事変
      - 亜人ちゃんは語りたい
      - アニメガタリズ
      - 異世界はスマートフォンとともに。
      - 妹さえいればいい。
      - うらら迷路帖
      - エロマンガ先生
      - ガヴリールドロップアウト
      - 賭ケグルイ
      - キノの旅 -the Beautiful World- the Animated Series
      - クジラの子らは砂上に歌う
      - クズの本懐
      - クロックワーク・プラネット
      - けものフレンズ
      - 恋と嘘
      - この素晴らしい世界に祝福を! 2
      - このはな綺譚
      - 小林さんちのメイドラゴン
      - 冴えない彼女の育て方♭
      - サクラクエスト
      - 終末なにしてますか? 忙しいですか? 救ってもらっていいですか?
      - 少女終末旅行
      - スクールガールストライカーズ Animation Channel
      - 正解するカド
      - セイレン
      - 探偵オペラ ミルキィホームズ アルセーヌ 華麗なる欲望
      - 徒然チルドレン
      - 天使の3P!
      - 捏造トラップ -NTR-
      - ひなこのーと
      - ひなろじ from Luck & Logic
      - 干物妹！うまるちゃんR
      - 武装少女マキャベリズム
      - プリンセス・プリンシパル
      - ブレンド・S
      - 僕の彼女がマジメすぎるしょびっちな件
      - 政宗くんのリベンジ
      - 結城友奈は勇者である -鷲尾須美の章-/-勇者の章-
      - 幼女戦記
      - ようこそ実力至上主義の教室へ
      - ラブライブ! サンシャイン!! (2期)
      - ロクでなし魔術講師と禁忌教典
    2018:
      - A.I.C.O. Incarnation
      - BanG Dream! ガルパ☆ピコ
      - citrus
      - Lostorage conflated WIXOSS
      - One Room セカンドシーズン
      - RELEASE THE SPYCE
      - SSSS.GRIDMAN
      - あそびあそばせ
      - 色づく世界の明日から
      - 宇宙よりも遠い場所
      - 音楽少女
      - からかい上手の高木さん
      - ゴールデンカムイ (シーズン2)
      - こみっくがーるず
      - 殺戮の天使
      - 邪神ちゃんドロップキック
      - シュタインズ・ゲート ゼロ
      - 少女☆歌劇 レヴュースタァライト
      - すのはら荘の管理人さん
      - スロウスタート
      - 青春ブタ野郎はバニーガール先輩の夢を見ない
      - ゾンビランドサガ
      - だがしかし (2機)
      - たくのみ。
      - デスマーチから始まる異世界狂想曲
      - 刀使ノ巫女
      - はたらく細胞
      - ハッピーシュガーライフ
      - 魔法少女サイト
      - 三ツ星カラーズ
      - メルヘンメドヘン
      - ラーメン大好き小泉さん
      - りゅうおうのおしごと!
      - やがて君になる
      - ヤマノススメ サードシーズン
      - ユリシーズ ジャンヌ・ダルクと錬金の騎士
      - ゆらぎ荘の幽奈さん
      - ゆるキャン△
    2019:
      - BanG Dream! 2nd Season
      - Z／X Code reunion
      - アサシンズプライド
      - 上野さんは不器用
      - うちの娘の為ならば、俺はもしかしたら魔王も倒せるかもしれない。
      - エガオノダイカ
      - かぐや様は告らせたい
      - かつて神だった獣たちへ
      - からかい上手の高木さん2
      - 可愛ければ変態でも好きになってくれますか？
      - 五等分の花嫁
      - この勇者が俺TUEEEくせに慎重すぎる
      - 世話やきキツネの仙狐さん
      - 川柳少女
      - ソウナンですか？
      - ノブナガ先生の幼な妻
      - ひとりぼっちの○○生活
      - ぼくたちは勉強ができない
      - 俺を好きなのはお前だけかよ
      - 魔王様リトライ
      - まちカドまぞく
      - 淫らな青ちゃんは勉強ができない
      - みにとじ
      - 約束のネバーランド
      - 私に天使が舞い降りた!
      - 私、能力は平均値でって言ったよね!
    2020:
      - ダーウィンズゲーム
