<!-- anime { -->
<section>

<h3>アニメ全般</h3>

<p>一般向けアニメも見ますが、深夜アニメが中心になります。</p>
<p>そのシーズンの話題作をすべて網羅してる訳ではないので、ご注意。</p>

</section>
<!-- } anime -->

<!-- anime list { -->
<section>

<h3>視聴済みアニメ</h3>

<p>放送年別。OVA は発売年。</p>
<p>最後まで視聴したもののみ。</p>

<ul>
<li>1998
	<ul>
	<li>serial experiments lain</li>
	</ul>
</li>
<li>2001
	<ul>
	<li>NOIR</li>
	</ul>
</li>
<li>2002
	<ul>
	<li>攻殻機動隊 STAND ALONE COMPLEX</li>
	</ul>
</li>
<li>2003
	<ul>
	<li>D.C. ～ダ・カーポ～</li>
	<li>プラネテス</li>
	<li>真月譚 月姫</li>
	<li>無人惑星サヴァイヴ</li>
	</ul>
</li>
<li>2004
	<ul>
	<li>この醜くも美しい世界</li>
	<li>ローゼンメイデン</li>
	<li>神無月の巫女</li>
	<li>攻殻機動隊 S.A.C. 2nd GIG</li>
	<li>魔法少女リリカルなのは</li>
	<li>妄想代理人</li>
	</ul>
</li>
<li>2005
	<ul>
	<li>AIR</li>
	<li>D.C.S.S. ～ダ・カーポ セカンドシーズン～</li>
	<li>LOVELESS</li>
	<li>SHUFFLE!</li>
	<li>イリヤの空、UFOの夏</li>
	<li>かみちゅ!</li>
	<li>苺ましまろ</li>
	<li>灼眼のシャナ</li>
	<li>撲殺天使ドクロちゃん</li>
	<li>魔法少女リリカルなのはA's</li>
	</ul>
</li>
<li>2006
	<ul>
	<li>Fate/stay night</li>
	<li>Kanon</li>
	<li>Soul Link</li>
	<li>Strawberry Panic</li>
	<li>xxxHOLiC</li>
	<li>うたわれるもの</li>
	<li>ゼロの使い魔</li>
	<li>はぴねす!</li>
	<li>ひぐらしのなく頃に</li>
	<li>攻殻機動隊 STAND ALONE COMPLEX Solid State Society</li>
	<li>涼宮ハルヒの憂鬱</li>
	<li>半分の月がのぼる空</li>
	<li>夜明け前より瑠璃色な</li>
	</ul>
</li>
<li>2007
	<ul>
	<li>School Days</li>
	<li>SHUFFLE! MEMORIES</li>
	<li>sola</li>
	<li>Venus Versus Virus</li>
	<li>この青空に約束を― ～ようこそつぐみ寮へ～</li>
	<li>ご愁傷さま二ノ宮くん</li>
	<li>ゼロの使い魔～双月の騎士～</li>
	<li>ななついろ★ドロップス</li>
	<li>のだめカンタービレ</li>
	<li>ひだまりスケッチ</li>
	<li>ひとひら</li>
	<li>まなびストレート!</li>
	<li>みなみけ</li>
	<li>もえたん</li>
	<li>らき☆すた</li>
	<li>苺ましまろ OVA</li>
	<li>京四郎と永遠の空</li>
	<li>灼眼のシャナII</li>
	<li>撲殺天使ドクロちゃん2</li>
	<li>魔法少女リリカルなのはStrikerS</li>
	</ul>
</li>
<li>2008
	<ul>
	<li>xxxHOLiC◆継</li>
	<li>かんなぎ</li>
	<li>とある魔術の禁書目録</li>
	<li>のだめカンタービレ 巴里編</li>
	</ul>
</li>
<li>2009
	<ul>
	<li>スラップアップパーティー -アラド戦記-</li>
	<li>そらのおとしもの</li>
	<li>とある科学の超電磁砲</li>
	<li>にゃんこい!</li>
	<li>苺ましまろ encore</li>
	<li>空中ブランコ</li>
	<li>灼眼のシャナS</li>
	</ul>
</li>
<li>2010
	<ul>
	<!-- あ -->
	<li>荒川アンダー ザ ブリッジ</li>
	<li>荒川アンダー ザ ブリッジx2</li>
	<li>Angel Beats!</li>
	<li>俺の妹がこんなに可愛いわけがない</li>
	
	<!-- か -->
	<li>神のみぞ知るセカイ</li>
	
	<!-- さ -->
	<li>侵略!イカ娘</li>
	<li>生徒会の一存</li>
	<li>そらのおとしものf</li>
	
	<!-- た -->
	<li>探偵オペラ ミルキィホームズ</li>
	
	<!-- な -->
	<li>のだめカンタービレ フィナーレ</li>
	
	<!-- ま -->
	<li>迷い猫オーバーラン!</li>
	</ul>
</li>
<li>2011
	<ul>
	<li>GOSICK -ゴシック-</li>
	<li>IS 〈インフィニット・ストラトス〉</li>
	<li>STEINS;GATE</li>
	<li>神のみぞ知るセカイII</li>
	<li>これはゾンビですか?</li>
	<li>灼眼のシャナIII (Final)</li>
	<li>フラクタル</li>
	<li>魔法少女まどか☆マギカ</li>
	<li>夢喰いメリー</li>
	</ul>
</li>
<li>2012
	<ul>
	<li>Another</li>
	<li>人類は衰退しました</li>
	<li>生徒会の一存 Lv.2</li>
	<li>ゼロの使い魔F</li>
	<li>探偵オペラ ミルキィホームズ 第2幕</li>
	</ul>
</li>
<li>2013
	<ul>
	<li>Fate/kaleid liner プリズマ☆イリヤ</li>
	<li>D.C.III ～ダ・カーポIII～</li>
	
	<!-- あ -->
	<li>石田とあさくら</li>
	<li>俺の彼女と幼なじみが修羅場すぎる</li>
	<li>俺の脳内選択肢が、学園ラブコメを全力で邪魔している</li>
	
	<!-- た -->
	<li>ダンガンロンパ 希望の学園と絶望の高校生 The Animation</li>
	<li>とある科学の超電磁砲S</li>
	<li>東京レイヴンズ</li>
	
	<!-- な -->
	<li>凪のあすから</li>
	<li>のんのんびより</li>
	
	<!-- は -->
	<li>変態王子と笑わない猫。</li>
	
	<!-- ま -->
	<li>問題児たちが異世界から来るそうですよ？</li>
	
	<!-- ら -->
	<li>ラブライブ！</li>
	
	<!-- や -->
	<li>ヤマノススメ</li>
	</ul>
</li>
<li>2014
	<ul>
	<!-- 英字 -->
	<li>Fate/kaleid liner プリズマ☆イリヤ 2wei!</li>
	<li>selector infected WIXOSS</li>
	<li>SHIROBAKO</li>
	
	<!-- あ -->
	<li>アカメが斬る！</li>
	<li>悪魔のリドル</li>
	
	<!-- か -->
	<li>彼女がフラグをおられたら</li>
	<li>グラスリップ</li>
	<li>月刊少女野崎くん</li>
	<li>極黒のブリュンヒルデ</li>
	<li>ご注文はうさぎですか？</li>
	
	<!-- さ -->
	<li>咲-Saki- 全国編</li>
	<li>桜Trick</li>
	<li>さばげぶっ！</li>
	<li>人生相談テレビアニメーション「人生」</li>
	<li>スペース☆ダンディ</li>
	<li>星刻の竜騎士</li>
	<li>生徒会役員共＊</li>
	<li>精霊使いの剣舞</li>
	
	<!-- た -->
	<li>東京喰種</li>
	<li>となりの関くん</li>
	
	<!-- な -->
	<li>ニセコイ</li>
	<li>のうりん</li>
	<li>ノーゲーム・ノーライフ</li>
	
	<!-- は -->
	<li>ハナヤマタ</li>
	<li>ばらかもん</li>
	<li>棺姫のチャイカ</li>
	<li>ひめゴト</li>
	<li>普通の女子校生が【ろこどる】やってみた。</li>
	<li>ブラック・ブレット</li>
	
	<!-- ま -->
	<li>まじもじるるも</li>
	<li>魔法科高校の劣等生</li>
	<li>マンガ家さんとアシスタントさんと</li>
	
	<!-- ら -->
	<li>ラブライブ！ (第2期)</li>
	<li>六畳間の侵略者!?</li>
	
	<!-- や -->
	<li>ヤマノススメ セカンドシーズン</li>
	<li>結城友奈は勇者である</li>
	</ul>
</li>
<li>2015
	<ul>
	<li>アブソリュート・デュオ</li>
	<li>銃皇無尽のファフニール</li>
	</ul>
</li>
</ul>
</section>
<!-- } anime list -->
