
<!-- site info { -->
<section>

<h3>サイト概要</h3>

<p>このウェブサイトは私、<strong>水音氷音 (ぴね)</strong> のプロフィールを自分自身でまとめたものです。</p>
<p>私に連絡を取りたい場合は、メニューの連絡先に記載されているものを利用してください。</p>
<p>Web サイトの内容は随時更新を行っていますが、古い内容が記載されている場合があります。</p>
<p>各ブラウザの最新バージョン、もしくは IE 6 以降でご覧ください。IE は 9 以降を推奨します。</p>
<p>HTML5・CSS3・PHP5 を使ってこのサイトを作成しています。</p>

</section>
<!-- } site info -->

<!-- simple profile { -->
<section>

<h3>簡単な自己紹介</h3>

<p>準備中

</section>
<!-- } simple profile -->

<!-- vim: se noet ts=4 sw=4 sts=4 ft=php : -->
