<!-- browser { -->
<section>

<h3>対応ブラウザ</h3>

<ul>
<li>フルサポート
	<p>想定しているデザインを完全に再現できるブラウザです。</p>
	
	<ul>
	<li>Firefox 4 以降</li>
	<li>Google Chrome 7 以降</li>
	<li>Opera 10.5 以降</li>
	<li>Safari 5 以降</li>
	</ul>
</li>
<li>部分サポート
	<p>対応していない機能があるため、レイアウトを意図的に変更して表示されます。</p>
	
	<ul>
	<li>Firefox 3.5 以降</li>
	<li>Internet Explorer 9</li>
	</ul>
</li>
<li>エミュレートサポート
	<p>対応していない機能を、JavaScript のエミュレートによって実現しているため、JavaScript が有効である必要があります。</p>
	
	<ul>
	<li>Internet Explorer 7-8</li>
	<li>Internet Explorer 6 (非推奨)</li>
	</ul>
</li>
</ul>

<p>なお、Internet Explorer 9 以降, Opera 11.10 以降, Chrome 9 以降では、背景画像のフォーマットとして、JPEG より圧縮率の高い形式を利用し、より高速な転送を実現しています。</p>
<p><small>※ Internet Explorer では JPEG XR, その他のブラウザでは WebP 形式を使用しています。</small></p>

</section>
<!-- } browser -->

<!-- thank { -->
<section>

<h3>謝辞</h3>

<p>このウェブサイトでは、以下のライブラリ･画像を利用させていただいています。</p>
<p>この場を借りて、お礼申し上げます。</p>

<ul>

<li><a href="http://code.google.com/p/html5shim/">html5shim</a>
<p>Internet Explorer 8 以前に HTML5 の新要素を認識させるライブラリ。</p>
</li>

<li><a href="http://code.google.com/p/html5resetcss/">html5resetcss</a>
<p>HTML5 に対応した CSS リセットライブラリ。</p>
</li>

<li><a href="http://code.google.com/p/ie7-js/">ie7-js</a>
<p>過去の Internet Explorer に存在しない機能をエミュレートするライブラリ。</p>
</li>

<li><a href="http://css3pie.com/">CSS3 PIE</a>
<p>Internet Explorer 6～8 で CSS3 の機能をエミュレートするライブラリ。</p>
</li>

<li><a href="http://www.yunphoto.net/">ゆんフリー写真素材集</a>
<p>背景画像として写真を利用させていただいています。</p>
</li>

</ul>

</section>
<!-- } thank -->